# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# The log directory
log_path: "/var/log/amanda/amanda-rest-server-log"

# Your application's name
appname: "amanda"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"

serializer: "JSON"

engines:
    JSON:
        allow_nonref:    '1'
        allow_blessed:   '1'
        pretty:          '1'
        convert_blessed: '1'

#        canonical:       '1'

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     start_tag: '[%'
#     end_tag:   '%]'


